
export default [
    {
        name: 'Liu Bei',
        country: 'Shu',
        health: 4,
        gender: 'M',
        isMonarch: true,
    },
    {
        name: 'Guan Yu',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhang Fei',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhuge Liang',
        country: 'Shu',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Zhao Yun',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Ma Chao',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Huang Yue Ying',
        country: 'Shu',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Sun Quan',
        country: 'Wu',
        health: 4,
        gender: 'M',
        isMonarch: true,
    },
    {
        name: 'Gan Ning',
        country: 'Wu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Lu Meng',
        country: 'Wu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Huang Gai',
        country: 'Wu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhou Yu',
        country: 'Wu',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Da Qiao',
        country: 'Wu',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Lu Xun',
        country: 'Wu',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Sun Shang Xiang',
        country: 'Wu',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Cao Cao',
        country: 'Wei',
        health: 4,
        gender: 'M',
        isMonarch: true,
    },
    {
        name: 'Sima Yi',
        country: 'Wei',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Xiahou Dun',
        country: 'Wei',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhang Liao',
        country: 'Wei',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Xu Chu',
        country: 'Wei',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Guo Jia',
        country: 'Wei',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Zhen Ji',
        country: 'Wei',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Hua Tuo',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Diao Chan',
        country: 'Kingdomless',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Lu Bu',
        country: 'Kingdomless',
        health: 4,
        gender: 'M',
    },

    // Wind Expansion
    {
        name: 'Wei Yan',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Huang Zhong',
        country: 'Shu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Xiahou Yuan',
        country: 'Wei',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Cao Ren',
        country: 'Wei',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Zhou Tai',
        country: 'Wu',
        health: 4,
        gender: 'M',
    },
    {
        name: 'Xiao Qiao',
        country: 'Wu',
        health: 3,
        gender: 'F',
    },
    {
        name: 'Zhang Jiao',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
    },
    {
        name: 'Yu Ji',
        country: 'Kingdomless',
        health: 3,
        gender: 'M',
    },
];
